# Generated by Django 3.1.5 on 2021-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVUserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
